### PR TITLE
Added functions getRetirementData and getPIAData which execute typica…

### PR DESCRIPTION
**Pull request by jdkingsley**
…l operations found in oasdir. They return lists of the calculations. Functions found in retirement.R

### CODE REVIEW

**Comment by twjacobs** [comment]
Hey Jeff, sorry for such a late pull. I'm accepting the request now.

**Comment by jdkingsley** [comment]
Hi Tim,

No problem...but I have been thinking about the package lately. I would like to run some scenarios based on some changes in our situation. I will not have time until mid-January or early February but I hope to get back to it then. Not sure if using the R package is the quickest way to explore my scenarios but I'd like to try...

Hope all is well!
________________________________

**Comment by twjacobs** [comment]
Hey Jeff,
Things are going pretty good but I'm getting cabin fever because my office is a little cut out in the apartment. So I go on walks when I can. You've got me worried when you say there is a change in your situation. Hope all is well with you too.

Tim

On Dec 5, 2017 1:03 PM, Jeffrey Kingsley <notifications@github.com> wrote:
Hi Tim,

No problem...but I have been thinking about the package lately. I would like to run some scenarios based on some changes in our situation. I will not have time until mid-January or early February but I hope to get back to it then. Not sure if using the R package is the quickest way to explore my scenarios but I'd like to try...

Hope all is well!
________________________________

**Comment by jdkingsley** [comment]
Oh, did not intend to startle or be obscure...

I heard a financial guy say the Social Security reserve has been "raided" by Obamacare funding. I have not been able to find any confirmation. His assertion was that the reserve would be gone sooner than 2035. I wanted to run scenarios that explore cuts to benefits.

The other change (I likely mentioned this before) is that Linda has been working part-time and has been contributing. I wanted to see if I could develop some code to explore impact of working part-time while receiving Social Security benefits vs. delaying benefits.

We've been busy planning for the Disney trip (early January). Looking forward to it!



________________________________

**Comment by twjacobs** [comment]
Oh, OK. I feel better. Hope your Disney trip is great!

On Dec 5, 2017 5:21 PM, Jeffrey Kingsley <notifications@github.com> wrote:
Oh, did not intend to startle or be obscure...

I heard a financial guy say the Social Security reserve has been "raided" by Obamacare funding. I have not been able to find any confirmation. His assertion was that the reserve would be gone sooner than 2035. I wanted to run scenarios that explore cuts to benefits.

The other change (I likely mentioned this before) is that Linda has been working part-time and has been contributing. I wanted to see if I could develop some code to explore impact of working part-time while receiving Social Security benefits vs. delaying benefits.

We've been busy planning for the Disney trip (early January). Looking forward to it!



________________________________

**Pull request merged**
